### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by KirstieJane** [cassgvp/git-for-collaborative-documentation#43]
Hi @cassgvp ! I'm loving these resources!!

I have a completely transparent motive with this issue which is that I think there are amazing materials here - the gifs in particular - and I think they could be an amazing addition to the Turing Way.

However, more generally, it would be great to have a license - even if that license says "all rights reserved" :)

What do you think?

**Comment by cassgvp** [comment]
Hi @KirstieJane 🤗,

I nearly gooped with shame at the idea of not having a license already! Turns out I do have one, but it’s a bit hidden. See https://cassgvp.github.io/github-for-collaborative-documentation/docs/LICENSE.html 😊. I’ll move it to the root directory when I’ve time to check it doesn’t break the rendered structure too much.

Thank you for your kind comments. I’m sure you recognise your “friendly tutorial” in there 😊. I would of course be honoured for any of it to appear in Turing Way, and very happy to review the addition.

C
